name: connectify
description: "A cross-platform social networking app built with Flutter and Supabase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  form_validator: ^2.1.1
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.3.2
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  uuid: ^4.3.3
  jiffy: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"

